package com.icodejava.research.nlp.domain;
/**
 * 
 * @author Kushal Paudyal
 * www.sanjaal.com | www.inepal.org
 * 
 * This class provides an enumeration of majority of the compound word endings in Nepali Language.
 * 
 * Created On: 4/1/2017
 * Last Modified On: 4/8/2017
 *
 */

public enum CompoundWordEnding {
	ANUSAR("अनुसार"),
	BAHEK("बाहेक"),
	BARE("बारे"),
	BATA("बाट"),
	BATAI("बाटै"), 
	BHANDAA("भन्दा"),
	BHAR("भर"),
	BHAYEKO("भएको"),
	BHAYEKI("भएकी"),
	BHAYO("भयो"),
	BHITRA("भित्र"),
	BHITRAI("भित्रै"),
	BHITRAKA("भित्रका"),
	BHITRAMA("भित्रमा"),
	BHITRA_SAMET("भित्रसमेत"),
	BICH_1("बीच"),
	BICH_2("बिच"),
	BICH_KO_1("बीचको"),
	BICH_KO_2("बिचको"),
	BICH_MA_1("बीचमा"),
	BICH_MA_2("बिचमा"),
	BIHEEN("बिहीन"),
	BIHEENAI("बिहीनै"),
	BIHIN("बिहिन"),
	BIHINAI("बिहिनै"),
	BINA("बिना"),
	BODH_1("बोध"),
	BODH_2("वोध"),
	DEKHI("देखि"),
	DWARA_1("द्वारा"),
	DWARA_2("द्धारा"),
	HARU_1("हरु"),
	HARU_2("हरू"),
	HARU_BICH_1("हरुबीच"),
	HARU_BICH_2("हरूबीच"),
	HARU_JHAIN_1("हरुझैं"),
	HARU_JHAIN_2("हरूझैं"),
	HARU_KAI_1("हरुकै"),
	HARU_KAI_2("हरूकै"),
	HARU_LAAI_1("हरुलाई"),
	HARU_LAAI_2("हरूलाई"),
	HARU_MADHYA_1("हरुमध्ये"),
	HARU_MADHYA_2("हरूमध्ये"),
	HARU_MADHYA_3("हरुमध्य"),
	HARU_MADHYA_4("हरूमध्य"),
	HARU_MATHI_1("हरुमाथि"),
	HARU_MATHI_2("हरूमाथि"),
	HARU_MATHI_3("हरुमाथी"),
	HARU_MATHI_4("हरूमाथी"),
	HARU_PRATI_1("हरुप्रती"),
	HARU_PRATI_2("हरूप्रती"),
	HARU_PRATI_3("हरुप्रति"),
	HARU_PRATI_4("हरूप्रति"),
	HARU_SAMET_1("हरुसमेत"),
	HARU_SAMET_2("हरूसमेत"),
	HARU_SANGA_1("हरुसंग"),
	HARU_SANGA_2("हरूसंग"),
	HARU_SANGA_3("हरुसँग"),
	HARU_SANGA_4("हरूसँग"),
	HARU_SANGA_5("हरुसङ्ग"),
	HARU_SANGA_6("हरूसङ्ग"),
	HARU_SANGA_KO_1("हरुसँगको"),
	HARU_SANGA_KO_2("हरूसंगको"),
	HARU_SANGA_KO_3("हरुसंगको"),
	HARU_SANGA_KO_4("हरूसँगको"),
	HARU_SANGA_KO_5("हरुसङ्गको"),
	HARU_SANGA_KO_6("हरूसङ्गको"),
	HARU_SANGAI_1("हरुसंगै"),
	HARU_SANGAI_2("हरूसंगै"),
	HARU_SANGAI_3("हरुसँगै"),
	HARU_SANGAI_4("हरूसँगै"),
	HARUBAATA_1("हरुबाट"), 
	HARUBAATA_2("हरूबाट"), 
	HARUBAATA_3("हरुवाट"), 
	HARUBAATA_4("हरूवाट"), 
	HARUDWARA_1("हरुद्धारा"),
	HARUDWARA_2("हरूद्धारा"),
	HARUKA_1("हरुका"),
	HARUKA_2("हरूका"),
	HARUKO_1("हरुको"),
	HARUKO_2("हरूको"),
	HARULAI_1("हरुलाइ"), 
	HARULAI_2("हरूलाइ"), 
	HARULAI_3("हरुलाई"), 
    HARULAI_4("हरूलाई"), 
	HARULE_1("हरुले"),
	HARULE_2("हरूले"),
	HARUMA_1("हरुमा"), 
	HARUMA_2("हरूमा"),
	HARUMAI_1("हरुमै"), 
	HARUMAI_2("हरूमै"),
	HARUSAMMA_1("हरुसम्म"),
	HARUSAMMA_2("हरूसम्म"),
	HARUSAMMAI_1("हरुसम्मै"),
	HARUSAMMAI_2("हरूसम्मै"),
	HARUSAMMA_MA_1("हरुसम्ममा"),
	HARUSAMMA_MA_2("हरूसम्ममा"),
	HARUSITA_1("हरुसित"),
	HARUSITA_2("हरूसित"),
	HARUSITAI_1("हरुसितै"),
	HARUSITAI_2("हरूसितै"),
	JASTA("जस्ता"),
	JASTAI("जस्तै"),
	JASTO("जस्तो"),
	JATI("जति"),
	JHAIN("झैं"),
	JYU_1("ज्यु"),
	JYU_2("ज्यू"),
	JYU_HARU_1("ज्युहरू"),
	JYU_HARU_2("ज्यूहरू"),
	JYU_HARU_3("ज्युहरु"),
	JYU_HARU_4("ज्यूहरु"),
	JI_HARU_1("जिहरू"),
    JI_HARU_2("जीहरू"),
    JI_HARU_3("जिहरु"),
    JI_HARU_4("जीहरु"),
    KA("का"),
	KAARI("कारी"),//E.G. BINASKARI
	KAHAN_1("कहाँ"),
	KAHAN_2("कहां"),
	KAHAN_3("काहाँ"),
	KAHAN_4("काहां"),
	KAI("कै"),
	KEE("की"),
	KHALKO("खालको"),
	KO("को"),
	KO_LAGI("कोलागी"),
	LAEE("लाई"),
	LAGAYAT("लगायत"),
	LAGAYATKA("लगायतका"),
	LAGAYATKO("लगायतको"),
	LAGAYATMA("लगायतमा"),
	LAI("लाइ"),
	LE("ले"),
	MA("मा"),
	MADHYA("मध्य"),
	MADHYAKA("मध्येका"),
	MADHYE("मध्ये"),
	MADHYEKA("मध्यका"),
	MAI("मै"),
	MAJHA("माझ"),
	MAJHAI("माझै"),
	MARPHAT("मार्फत"),
	MARPHATAI("मार्फतै"),
	MATHEE("माथी"),
	MATHEEKO("माथीको"),
	MATHI("माथि"),
	MATHIKO("माथिको"),
	MATRAI("मात्रै"),
	MAYA("मय"),
	MOOLAK_1("मुलक"),
	MOOLAK_2("मूलक"),
	MUKHI("मुखी"),
	MUNI_1("मुनि"),
	MUNI_2("मुनी"),
	MUNTIRA("मुन्तिर"),
	PACHHI_1("पछि"),
	PACHHI_2("पछी"),
	PACHHIKA("पछिका"),
	PARNE("पर्ने"),
	PASCHAT_1("पश्चात"),
	PASCHAT_2("पस्चात"),
	PASCHAT_3("पश्चात्"),
	POORBAK_1("पुर्बक"),
	POORBAK_2("पूर्बक"),
	POORBAK_3("पुर्वक"),
	POORBAK_4("पूर्वक"),
	POORBA_1("पूर्व"),
    POORBA_2("पुर्व"),
    POORBA_3("पुर्ब"),
    POORBA_4("पूर्ब"),
    POORBA_KAI_1("पूर्वकै"),
    POORBA_KAI_2("पुर्वकै"),
    POORBA_KAI_3("पुर्बकै"),
    POORBA_KAI_4("पूर्बकै"),
	PRATI("प्रति"),
	PURNA_1("पूर्ण"), 
	PURNA_2("पुर्ण"),
	RAKHEKO("राखेको"),
	SAATH("साथ"),
	SAATHAI("साथै"),
	SAHIT("सहित"),
	SAHITAI("सहितै"),
	SAHITKA_1("सहितका"),
	SAHITKA_2("सहीतका"),
	SAKEKA("सकेका"),
	SAKEKO("सकेको"),
	SAMAKSHA("समक्ष"),
	SAMBANDHI("सम्बन्धी"),
	SAMET("समेत"),
	SAMETAI("समेतै"),
	SAMMA("सम्म"),
	SAMMAI("सम्मै"),
	SAMMAKO("सम्मको"),
	SAMMALE("सम्मले"),
	SAMMAMA("सम्ममा"),
	SANGA_1("सँग"),
	SANGA_2("संग"),
	SANGA_3("सङ्ग"),
	SANGAI_1("संगै"),
	SANGAI_2("सँगै"),
	SANGAI_3("सङ्गै"),
	SANGAKO("संगको"),
	STHIT("स्थित"), 
	TARFA("तर्फ"),
	TARFAKO("तर्फको"),
	TEERA("तीर"),
	TIRA("तिर"),
	VARE("वारे"),
	VATA("वाट"),
	VEECH("वीच"),
	VICH("विच"),
	VIHEEN("विहीन"),
	VIHIN("विहिन"), 
	VIRUDDHA("विरुद्ध"),
	YOS_1("योस"),
	YOS_2("योस्"),
	BHARI_1("भरि"),
	BHARI_2("भरी"),
	SAMU_1("सामु"),
	SHEEL("शील"),
	YUKTA("युक्त");
	/*
	 * भाव अघि पाटनहरूमै बित्तिकैदेखि जत्तिकै पूर्वकै रोल्पावासी Yatra
	 * चोटिमा Patak करण (e.g. Adhunikikaran, bargikaran घारणात्मक चौरको वाणी
	 * बस्न्परेको बिघटनपछिको अनुरुप तन्नाकोलागी भइसकेकाले हत्यापछाडिको
	 * 
	 * verbs हुन्छ गाउछौं / उभिन्छौं जोडीएर पछुताउँथे नछुट्टाएर होइनन
	 * बिर्सिदिन्छु देवकोटाजीकै साबिकै अधिनायकत्व खोजिरहेकाहरू
	 */

	private String nepaliWordEnding;

	CompoundWordEnding(String nepaliWordEnding) {

		this.nepaliWordEnding = nepaliWordEnding;
	}

	public String getNepaliWordEnding() {

		return nepaliWordEnding;
	}
	
}
